from .experiment import Stage, StageData, StageParameter, PipelineData, dist_parser
from .distributions import Distribution, UniformDistribution, NormalDistribution, ConstantDistribution, DISTRIBUTIONS

import numpy as np

def noise_dist_parser(payload):
    if issubclass(payload, Distribution):
        return payload
    if not isinstance(payload, str):
        raise ValueError("QuantNoise distribution must be a string or "
                         "distribution class.")
    if payload not in DISTRIBUTIONS:
        raise ValueError(f"Unknown distribution type: '{payload}'.")
    return DISTRIBUTIONS[payload].cls

def noise_scale_parser(payload):
    if isinstance(payload, Distribution):
        return payload
    if isinstance(payload, (float, int)):
        return ConstantDistribution(payload)
    raise ValueError("QuantNoise scale must be a distribution or a number.")
    

class QuantNoiseStage(Stage):
    """Apply quantitative noise to the intensity matrix

    Noise is generated by a user-specified distribution type (ex. "normal") that
    is applied to each value in the intensity matrix. The distribution will
    be centered on the intensity value (e.g. for "normal", the distribution
    mean will be set to the incoming intensity value), whereas the width of
    the distribution is determined by the formula:
    noise_scale * (intensity ** noise_exponent).
    For example, if `noise_distribution="uniform", `noise_exponent=0.5`, and
    `noise_scale = 0.25`, then for each incoming intensity, the result
    will be uniformly distributed in `intensity +/- sqrt(intensity)/4`

    In order to account for some samples being noisier than others, the
    `noise_scale` parameter is a distribution, s.t. each sample has a randomly
    selected scale.
    
    """
    REQUIRES = ["abundance"]

    noise_scale = StageParameter(Distribution,
                                 ConstantDistribution(0.2),
                                 msg_parser=noise_scale_parser)
    noise_distribution = StageParameter(type, NormalDistribution,
                                        msg_parser=noise_dist_parser)
    noise_exponent = StageParameter(float, 0.5)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
    def default_name(self) -> str:
        return "QuantNoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        # Compute per-sample noise scale, and force it into an abundance-shaped
        # matrix
        assert input.abundance is not None
        scale = state.noise_scale(input.abundance.shape[0], rng=rng)
        scale = np.ones(input.abundance.shape[1]) * scale[:, None]
        presence = input.abundance > 0
        vals = input.abundance[presence]
        noise_range = scale[presence] * vals**state.noise_exponent
        dist = state.noise_distribution(defaults = dict(
            def_min=(vals - noise_range),
            def_max=(vals + noise_range),
            def_mean=vals,
            def_var=noise_range))
        result = np.zeros_like(input.abundance)
        # Finally, apply the distribution:
        result[presence] = dist(len(vals), rng=rng)
        return PipelineData(input.copy(abundance=result), messages=[], rng=rng)


class ScaleBaseResponse(Stage):
    """Scale the base response to get into a range for presence absence noise.
    """
    REQUIRES = ["abundance", "base_response"]
    PROVIDES = ["abundance", "base_response"]

    prob_scale = StageParameter(float, 0.2)
    zero_frac = StageParameter(float, 0.0)
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
    def default_name(self) -> str:
        return "PresenceAbsenceNoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        # Compute per-sample noise scale, and force it into an abundance-shaped
        # matrix
        assert input.abundance is not None
        assert input.base_response is not None

        presence = input.base_response > 0
        
        dat = input.base_response[presence]
        if state.zero_frac > 0:
            if (state.zero_frac > 1):
                raise ValueError("'zero_frac' must be between 0 and 1.")
            # To get a certain fraction of expected zeros, we would ideally
            # map the data uniformly to [1-zfrac, 1].
            # Instead, we'll map the median to 1-zfrac
            zval = np.median(dat)
            prob_exp = np.log(1-state.zero_frac) / np.log(zval)
        else:
            prob_exp = state.prob_scale

        # Now, compare our scaled exponent
        dat = np.pow(dat, prob_exp)

        result = input.base_response.copy()
        result[presence] = dat
        return PipelineData(input.copy(base_response=result), messages=[], rng=rng)


class PresenceAbsenceNoise(Stage):
    """Zero out abundance randomly, based on the base_response matrix
    """
    REQUIRES = ["abundance", "base_response"]
    PROVIDES = ["abundance", "base_response"]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
    def default_name(self) -> str:
        return "PresenceAbsenceNoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        # Compute per-sample noise scale, and force it into an abundance-shaped
        # matrix
        assert input.abundance is not None
        assert input.base_response is not None

        rando = rng.uniform(size=input.base_response.shape)
        return PipelineData(input.copy(
            abundance=np.where(rando<input.base_response, input.abundance, 0)),
            messages=[], rng=rng)



    
class CommonNoise(Stage):
    """Apply per-sample or per-metabolite noise.

    Noise is generated by a user-specified distribution type (ex. "normal") that
    is applied by multiplying a random factor to each value in the intensity
    matrix.
    
    """
    REQUIRES = ["abundance"]

    noise_distribution = StageParameter(Distribution, UniformDistribution(0,8),
                                        msg_parser=dist_parser)

    def __init__(self, common_axis: str = "sample", **kwargs):
        if common_axis not in ("sample", "metabolite"):
            raise ValueError("common_axis must be 'sample' or 'metabolite'")
        self.common_axis = 0 if common_axis == "sample" else 1
        super().__init__(**kwargs)
        
    def default_name(self) -> str:
        return "QuantNoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        # Compute per-sample noise scale, and force it into an abundance-shaped
        # matrix
        assert input.abundance is not None
        N = input.abundance.shape[self.common_axis]
        scale = state.noise_distribution(N, rng=rng)
        
        # Apply the noise uniformly across the other axis
        if self.common_axis == 0:
            scale = scale[:, None]
        else:
            scale = scale[None, :]

        abundance = input.abundance * scale
        return PipelineData(input.copy(abundance=abundance), messages=[], rng=rng)

class ESINoise(Stage):
    """Apply noise based on a model of charge competition in ESI-MS.

    The model used is generalized from Enke, 1997 (A Predictive Model for Matrix
    and Analyte Effects in Electrospray Ionization of Singly -Charged
    Ionic Analytes. Analytical Chemistry 1997, 69, 4885-4893).

    The model used assumes that there is an equilibrium between charged species
    on the surface of the droplets (which eventually enter the gas phase and
    are transferred to the detector), and neutral ion/counterion pairs in the
    interior. Equations for the concentrations of charged surface species are
    derived, which depend on the total ion current, the analytical concentrations,
    and equilibrium constants for each species.

    For this simulation, we assign random equilibrium constants to each metabolite,
    drawn from the specified distribution.
    
    For simplicity, we assume the total ion current is equal to the total
    concentration of all metabolites in the incoming sample.

    As discussed in the Enke paper, the exact values of the equilibrium constants
    is not as important as their pairwise ratios. Thus, care should be taken to
    assume the ratios fall within a reasonable range.
    
    """
    REQUIRES = ["abundance"]

    k_distribution = StageParameter(Distribution, UniformDistribution(1,100),
                                        msg_parser=dist_parser)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
    def default_name(self) -> str:
        return "ESINoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        assert input.abundance is not None
        N = input.abundance.shape[1]
        Q = input.abundance.sum(axis=1)
        # First, assign random equilibrium constants to each metabolite        
        consts = state.k_distribution(N, rng=rng)

        # Charged Concentration = (K * C) / (sum(K_i * C_i))
        scaled = input.abundance * consts[None, :]
        denom = scaled.sum(axis=1)

        result = scaled / denom[:, None] * Q[:, None]

        return PipelineData(input.copy(abundance=result), messages=[], rng=rng)


class CompetitionStage(Stage):
    
    mean_interactors = StageParameter(float, 3)
    interaction = StageParameter(Distribution, UniformDistribution(0, .3))
    
    REQUIRES = ["abundance"]

    def default_name(self) -> str:
        return "Competition"

    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        import scipy.sparse as SP

        assert input.abundance is not None
        n_spcs = input.abundance.shape[1]
        density = state.mean_interactors / n_spcs
        # Generate a sparse interaction matrix with coefficients drawn from
        # the specified distribution.
        mat = SP.random_array((n_spcs, n_spcs), density=density,
                              data_sampler=lambda size: state.interaction(size, rng=rng),
                              rng=rng)
        # Get rid of self-interactions
        mat -= mat * SP.eye(n_spcs, n_spcs)

        # '@' means matrix multiply
        result = input.abundance - input.abundance @ mat

        result[result < 0] = 0

        return PipelineData(input.copy(abundance=result),
                            messages=[], rng=rng)

