from .experiment import Stage, StageData, StageParameter, PipelineData
from .distributions import Distribution, UniformDistribution, NormalDistribution, ConstantDistribution, DISTRIBUTIONS

import numpy as np

def noise_dist_parser(payload):
    if issubclass(payload, Distribution):
        return payload
    if not isinstance(payload, str):
        raise ValueError("QuantNoise distribution must be a string or "
                         "distribution class.")
    if payload not in DISTRIBUTIONS:
        raise ValueError(f"Unknown distribution type: '{payload}'.")
    return DISTRIBUTIONS[payload].cls

def noise_scale_parser(payload):
    if isinstance(payload, Distribution):
        return payload
    if isinstance(payload, (float, int)):
        return ConstantDistribution(payload)
    raise ValueError("QuantNoise scale must be a distribution or a number.")
    

class QuantNoiseStage(Stage):
    """Apply quantitative noise to the intensity matrix

    Noise is generated by a user-specified distribution type (ex. "normal") that
    is applied to each value in the intensity matrix. The distribution will
    be centered on the intensity value (e.g. for "normal", the distribution
    mean will be set to the incoming intensity value), whereas the width of
    the distribution is determined by the formula:
    noise_scale * (intensity ** noise_exponent).
    For example, if `noise_distribution="uniform", `noise_exponent=0.5`, and
    `noise_scale = 0.25`, then for each incoming intensity, the result
    will be uniformly distributed in `intensity +/- sqrt(intensity)/4`

    In order to account for some samples being noisier than others, the
    `noise_scale` parameter is a distribution, s.t. each sample has a randomly
    selected scale.
    
    """
    REQUIRES = ["abundance"]

    noise_scale = StageParameter(Distribution,
                                 ConstantDistribution(0.2),
                                 msg_parser=noise_scale_parser)
    noise_distribution = StageParameter(type, NormalDistribution,
                                        msg_parser=noise_dist_parser)
    noise_exponent = StageParameter(float, 0.5)

    def __init__(self):
        super().__init__()
        
    def default_name(self) -> str:
        return "QuantNoise"


    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        # Compute per-sample noise scale, and force it into an abundance-shaped
        # matrix
        assert input.abundance is not None
        scale = state.noise_scale(input.abundance.shape[0], rng=rng)
        scale = np.ones(input.abundance.shape[1]) * scale[:, None]
        presence = input.abundance > 0
        vals = input.abundance[presence]
        noise_range = scale[presence] * vals**state.noise_exponent
        dist = state.noise_distribution(defaults = dict(
            def_min=(vals - noise_range),
            def_max=(vals + noise_range),
            def_mean=vals,
            def_var=noise_range))
        result = np.zeros_like(input.abundance)
        # Finally, apply the distribution:
        result[presence] = dist(len(vals), rng=rng)
        return PipelineData(input.copy(abundance=result), messages=[], rng=rng)



class CompetitionStage(Stage):
    
    mean_interactors = StageParameter(float, 3)
    interaction = StageParameter(Distribution, UniformDistribution(0, .3))
    
    REQUIRES = ["abundance"]

    def default_name(self) -> str:
        return "Competition"

    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        import scipy.sparse as SP

        assert input.abundance is not None
        n_spcs = input.abundance.shape[1]
        density = state.mean_interactors / n_spcs
        # Generate a sparse interaction matrix with coefficients drawn from
        # the specified distribution.
        mat = SP.random_array((n_spcs, n_spcs), density=density,
                              data_sampler=lambda size: state.interaction(size, rng=rng),
                              rng=rng)
        # Get rid of self-interactions
        mat -= mat * SP.eye(n_spcs, n_spcs)

        # '@' means matrix multiply
        result = input.abundance - input.abundance @ mat

        result[result < 0] = 0

        return PipelineData(input.copy(abundance=result),
                            messages=[], rng=rng)

