from __future__ import annotations

import pandas as pd
import numpy as np
from typing import Dict, List
import dataclasses
from collections import defaultdict
from copy import deepcopy

from .experiment import Stage, StageData, PipelineData, Message, dist_parser
from .distributions import (
    RNG,
    Distribution,
    ConstantDistribution,
    ChoiceDistribution,
    UniformDistribution,
    LogNormalDistribution,
    )

from ._core import MassTracker, MODE_STRICT, ProfileGenerator, TransformList
from ._core import RNG as cRNG

@dataclasses.dataclass
class ProfileResult:
    indices: np.ndarray
    intensities: np.ndarray



class ProfileGroupConfig:
    class ResponseSet:
        def __init__(self, config, masses, profiles, stats=None):
            self.config = config
            self.masses = masses
            self.profiles = profiles
            self.stats = stats

        def apply(self, spcs_abundance):
            """
            Given a matrix where rows are samples and columns are species,
            return a new matrix with (n_samples, n_masses)
            """
            result = np.zeros((spcs_abundance.shape[0], len(self.masses)))
            assert spcs_abundance.shape[1] == len(self.profiles)
            # Basically, for each species, multiply its abundance (across
            # all samples) by its metabolic profile.
            for idx, prof in enumerate(self.profiles):
                result[:, prof.indices] += (spcs_abundance[:, idx][:, None]
                                            * prof.intensities)
            return result

    def __init__(self,
                 n_species: int,
                 n_target_masses: int,
                 transform_data: pd.DataFrame,
                 initial_components: int | Distribution,
                 initial_masses: List[float] | Distribution,
                 initial_intensities: int | float | Distribution | None = None,
                 initial_normalize: float | None = None,
                 intensity_scale: Distribution | None = None,
                 min_intensity: float = 1e-6,
                 tolerance_ppm: float = 1.0,
                 min_mass: float = 150,
                 max_mass: float = 1200,
                 pre_weight: float = 1,
                 weight_exponent: int = 2):

        """Configure a generator which produces "metabolic profiles"
        for a group of species.

        A metabolic profile is essentially a "mini-spectrum", or a
        list of masses and intensities.  Each species gets its own
        profile, and the set of species profiles can combined with
        species abundance to produce output spectra.

        Profile generation occurs in two steps, initialization and transformation.

        In initialization, profiles (one per species) are initialized
        with some number (relatively small, but at least one) peaks. The number of peaks in each
        profile, as well as peak attributes, are drawn from distributions given by the
        `initial_...` args.


        Transformation applies an iterative process to generate new
        peaks from existing ones.  Each iteration consists of choosing
        a transformation to apply, a profile, and a parent peak within
        t the profile.  New peak masses are generated by applying the
        mass_delta from the transformation to the parent peak one or
        more times (forward and/or backward).  The intensity of the
        new peaks is generated by scaling the parent peak by `intensity_scale`.
        The process is repeated until `n_target_masses` peaks are generated.

        Transformations are chosen based on probabilities given in the
        input `transform_data`. One might expect that simply applying
        transformations drawn using those probabilities will yield a
        dataset that has the same proportion of
        transformations. However this is not the case; many
        biochemical transformations can by built up as linear
        combinations of others.  Thus if you look at the
        transformation graph (aka Mass Diference Network, or MDiN) of
        the result, many new edges arise spontaneously. Even if you
        restrict yourself to some linearly independent set of
        transformations, the error caused by having a non-zero
        tolerance (even sub-parts-per-million) causes many
        unanticipated transformations to appear. In particular,
        extremely common transformations like methylation (+14.01565
        Da) that are substituents of many others appear relatively
        much less frequently than desired.

        To get around that, and to attempt to produce output datasets
        with similar transformation networks as real data, massim uses
        a weigting strategy.  As new peaks are added, massim tracks
        the changes to the MDiN, updating the number of
        transformations added directly *or indirectly*. Then, when it
        comes time to select a mass delta (aka Mass Difference
        Building Block, or MDB), massim weights the probability of
        each MDB by:

                                                        
        |  (desired fraction of MDB) * (1 + preweight) |**(weight_exponent)
        |  ------------------------------------------  |
        |   (current fraction of MDB + preweight)      |

        (The preweight is there mainly to control the early stages of
        the process, when the current fraction is low/zero)

        Thus, if a 
        

        
        However, naively drawing transformations (really, mass deltas)
        according to those probabilities will not yield
        
        Massim applies a probability weighting scheme to try to get the transformation counts
        of the output to 

        Args:
            n_species: Number of species to create profiles for.
            n_target_masses: Desired total number of peaks. The actual
                output might exceed this slightly.
            transform_data: A pandas DataFrame containing the
                biochemical transformations to apply. It must contain
                the columns:
            initial_components: Number of peaks to initially assign to
                each profile. Can be an integer, or a distrubution
                that will be drawn from for each profile. A minimum of
                one peak will be added to each profile.
            initial_masses: A fixed mass, list of masses, or
                distribution that will be used to populate the initial
                peaks. If it is a float, all profiles will be
                initialized with the same mass. If it's a list, massim
                will build a ChoiceDistribution from it.
            initial_intensities: A fixed scalar intensity or
                distribution used to choose the intensities of the
                initial peaks. Note that it can return negative vales,
                which can be used as a form of competition.
            intensity_scale: Scale factor to use when applying
                transformations. Each time a transformation is applied
                to a peak, the new peak's intensity will be this scale
                factor times the paren peak's intensity (and the
                parent intensity is reduced accordingly). May be a
                scalar or distribution, but should only return values
                from 0 to 1.
            initial_normalize: If set, all profiles will be normalized
                to sum to this value before transforms are applied.
                (the transformation process preserves the sum, so
                the final profiles will also sum to this)
            min_intensity: Minimum intensty of any new peak. If a new
                peak falls below this threshold, the current
                transformation is aborted.
            tolerance_ppm: Mass tolerance in parts per million. If a
                new peak is within this tolerance of an existing peak,
                it will be merged with the existing one.
            min_mass: Minimum mass to be produced during
                transformation.
            max_mass: Maximum mass to produce during transformation.
            pre_weight: Part of the probability weighting scheme.
            weight_exponent: Used to select transformation to apply.

        """
        """Configure a generator which produces "metabolic profiles"
        for a group of species.

        A metabolic profile is essentially a "mini-spectrum", or a
        list of masses and intensities.  Each species gets its own
        profile, and the set of species profiles can combined with
        species abundance to produce output spectra.

        Profile generation occurs in two steps. In the first step,
        profiles (one per species) are initialized with relatively few
        peaks, which are assigned according to the `initial_..`
        parameters.  Then, new metabolites are generated by applying
        simulated biochemical transformations to randomly selected
        peaks from randomly selected profiles. This process repeats until the
        total number of distinct peaks (across all profiles) reaches a target level.

        Parameters:
        

        """
        self.n_species = n_species
        self.n_target_masses = n_target_masses
        if isinstance(initial_components, (int, float)):
            initial_components = ConstantDistribution(initial_components)
        elif not isinstance(initial_components, Distribution):
            raise ValueError("'initial_components' must be an integer or distribution.")
        self.initial_components = initial_components

        if intensity_scale is None:
            intensity_scale = UniformDistribution(0, 1)
        if not isinstance(intensity_scale, Distribution):
            raise ValueError("`intensity_scale` must be a distribution.")
        try:
            intensity_scale.to_cdist()
        except RuntimeError:
            raise ValueError(f"Sadly, distribution type `{intensity_scale.shortname}` "
                             "isn't supported for profiles yet.")
        self.intensity_scale = intensity_scale

        if not isinstance(initial_masses, Distribution):
            if isinstance(initial_masses, (int, float)):
                initial_masses = ChoiceDistribution([initial_masses])
            elif hasattr(initial_masses, "__len__"):
                if not all(isinstance(x, (int, float)) for x in initial_masses):
                    raise ValueError("`initial_masses` must be a float, list of floats, or distribution.")
                initial_masses = ChoiceDistribution([x for x in initial_masses])
            else:
                raise ValueError("`initial_masses` must be a float, list of floats, or distribution.")
        self.initial_masses = initial_masses

        if initial_intensities is None:
            initial_intensities = LogNormalDistribution(0, 1)
        if isinstance(initial_intensities, (int, float)):
            initial_intensities = ConstantDistribution(initial_intensities)            
        if not isinstance(initial_intensities, Distribution):
            raise ValueError("`initial_intensities` must be a distribution.")
        self.initial_intensities = initial_intensities

        self.initial_normalize = initial_normalize

        
        # Initialize information about transformations
        # While passed as a dataframe, we store a list of rows, since oddly
        # pd.DataFrame.iloc is extremely slow in tight loops.
        self.xkeys = transform_data
        self.xkeys = self.xkeys.replace(np.nan, 0)
        self.xkeylist = [x for _, x in self.xkeys.iterrows()]

        self.raw_probs = (self.xkeys.chain_prob.values * (self.xkeys.chain_len - 1).values)
        self.raw_probs = self.raw_probs / self.raw_probs.sum()

        self.min_intensity = min_intensity
        self.tolerance_ppm = tolerance_ppm
        self.min_mass = min_mass
        self.max_mass = max_mass

                                     
        # Initialize the weighting factors for picking transforms
        if pre_weight <= 0:
            raise ValueError("Pre-weight must be positive.")
        self.pre_weight = pre_weight
        self.weight_exp = weight_exponent

    def generate_response(self, rng=None, return_worker=False):
        rng = RNG(rng)

        # Seed our c++ RNG from our python RNG.
        # This is a very poor seeding strategy, but suffices for now.
        # We're not doing cryptographic analysis or anything!
        c_rng = cRNG(rng.integers(2**30))

        tf_list = TransformList(np.array(self.xkeys.mass_delta),
                                np.array(self.xkeys.chain_prob),
                                np.array(self.xkeys.chain_len),
                                # unused:
                                np.array(self.xkeys.chain_prob),
                                False, False)

        xformer = ProfileGenerator(self.n_species,
                                   tf_list,
                                   self.intensity_scale.to_cdist(),
                                   self.min_mass,
                                   self.max_mass,
                                   self.min_intensity,
                                   self.tolerance_ppm,
                                   self.pre_weight,
                                   self.weight_exp)
        # Termination should be off by default, but double ensure.
        xformer.enable_termination = False
                                   
                                   
        # Populate the profiles with initial components
        for spcs_id in range(self.n_species):
            # Choose number of components per profile by sampling the distribution
            num_core = self.initial_components(1, rng=rng)[0]
            num_core = max(1, int(num_core))

            masses = self.initial_masses(num_core, rng=rng)
            intensities = self.initial_intensities(num_core, rng=rng)
            if self.initial_normalize is not None:
                intensities /= intensities.sum()
                intensities *= self.initial_normalize
            for w, m in zip(intensities, masses):
                xformer.update_component(spcs_id, m, w)

        # Now, just run it:
        xformer.apply_transforms(self.n_target_masses, rng=c_rng)
        stats = dict(xformer.stats())

        # Some stats about how many xfrms we applied, and how many were detected.
        stats["xfrm_counts"] = xformer.counts()

        # Convert C++ result struct into a python dataclass.
        # Needed, because we may deepcopy the data, which mean the C++
        # struct would need to be pickleable. 
        profs = [ProfileResult(x.indices, x.intensities)
                 for x in xformer.profiles()]
        result = ProfileGroupConfig.ResponseSet(self,
                                                xformer.masses(),
                                                profs,
                                                stats=stats)
        # For debugging:
        if return_worker:
            return result, xformer
        
        return result
        

def _merge_masses(mass_groups: Dict[np.ndarray], tolerance):
    """
    Merge multiple mass lists together into a single list so that:
    - each mass in each input mass list gets mapped to a single
      location in the output
    - "close" masses (within tolerance) are merged together,
      subject to the above constraint (i.e. two masses from the
      same mass_group will never be merged).

    Input is to be a dictionary of numpy arrays representing masses.
    
    Returns the combined mass list, as well as dict with the same
    keys as the input. The value is an array of indices that map
    each input mass to its location in the output.
    """
    
    keys = dict(zip(mass_groups, range(len(mass_groups))))

    # There's a lot of moving parts here. We are merging multiple groups
    # of masses. We first generate an array of all the masses, as well
    # a parallel array of the parent group of each mass

    all_masses = np.concatenate([mass_groups[k] for k in mass_groups]) 
    parents = np.concatenate([idx * np.ones_like(mass_groups[k], dtype=int)
                              for idx, k in enumerate(mass_groups)])

    # Now, we just sort them in parallel in order of ascending mass
    ordd = np.argsort(all_masses)
    all_masses = all_masses[ordd]
    parents = parents[ordd]


    # We are going to merge masses that are within tolerance of each other
    # The output will be at most as large as all inputs combined.
    # Initialize a large array for the output; we'll trim it down later.
    # We also keep track of where to insert the next mass
    out_masses = np.zeros_like(all_masses)
    out_idx = 0

    # In addition, we have to keep track of where each parent mass ends up
    # in the output. Each parent mass will get mapped to some index in
    # `out_masses`, so we reserve space for these indices. We call the
    # 'locations` to disambguate from all the other indices.
    # We also keep a pointer to the next location to insert
    parent_locations = [[np.zeros_like(mass_groups[k], dtype=np.int32), 0] for k in mass_groups]


    # As we scan through all masses, we gather adjacent close masses in a
    # `bucket`. This is the index of the first mass in the bucket
    bucket_start_idx = 0

    # We also keep track of which groups are in the bucket. Never add the same
    # parent more than once to the bucket
    seen_parents = np.zeros(len(mass_groups), dtype=bool)

    # The final setup is to initialize our bucket with the first mass/parent
    seen_parents[parents[0]] = True
    mass_bucket = all_masses[0]

    for cur_in_idx, cur_mass in enumerate(all_masses[1:], start=1):
        cur_parent = parents[cur_in_idx]
        
        # All the masses in the bucket get averaged together
        last_mass = mass_bucket / (cur_in_idx - bucket_start_idx)
        
        # We stop gathering masses if either the tolerance is exceeded, or
        # we have two masses from the same parent group
        if (cur_mass - last_mass) / cur_mass >= tolerance or seen_parents[cur_parent]:
            out_masses[out_idx] = last_mass
            # For all parents in the bucket, add the output index to their locations
            # and increment the location pointer
            for parent_idx, (out_loc, loc_idx) in enumerate(parent_locations):
                if seen_parents[parent_idx]:
                    out_loc[loc_idx] = out_idx
                    parent_locations[parent_idx][1] += 1
            out_idx += 1
            # reset the bucket to start at current index
            seen_parents[:] = 0
            bucket_start_idx = cur_in_idx
            mass_bucket = 0

        # Now, add the current mass to the (possibly freshly reset) bucket
        mass_bucket += cur_mass
        seen_parents[cur_parent] = True

    # Finally, we have to clear out the last bucket
    out_masses[out_idx] = mass_bucket / (len(all_masses) - bucket_start_idx)
    for parent_idx, (out_loc, loc_idx) in enumerate(parent_locations):
        if seen_parents[parent_idx]:
            out_loc[loc_idx] = out_idx
            parent_locations[parent_idx][1] += 1
        assert parent_locations[parent_idx][1] == len(out_loc)

    return out_masses[:out_idx+1], {grp_name: locs[0]
                                    for grp_name, locs in zip(mass_groups.keys(), parent_locations)}

        

    

class GenProfileStage(Stage):
    """
    """
    PROVIDES = ["profile_responses"]

    def default_name(self) -> str:
        return "GenProfiles"

    def __init__(self, profile_configs: ProfileGroupConfig | Dict[str, ProfileGroupConfig], **kwargs):
        if isinstance(profile_configs, ProfileGroupConfig):
            self.profile_configs = {None: profile_configs}
        else:
            if not (isinstance(profile_configs, dict) and
                    all(isinstance(v, ProfileGroupConfig) for v in profile_configs.values())):
                raise ValueError("`profile_configs` must be either a ProfileConfigGroup or a dict of such.")
            assert isinstance(profile_configs, dict)
            self.profile_configs = profile_configs
        super().__init__(**kwargs)

    def execute(self,
                input: StageData,
                rng: np.random.Generator,
                state: GenProfileStage.State) -> PipelineData:
        profile_responses = {}
        for group, config in state.profile_configs.items():
            profile_responses[group] = config.generate_response(rng=rng)
        result = PipelineData(input.copy(extra={"profile_responses": profile_responses}),
                              messages=[],
                              rng=rng)
        return result        

    class State(Stage.State):
        def __init__(self, stage: GenProfileStage):
            super().__init__(stage)
            self.profile_configs = dict((k, deepcopy(v)) for k, v in stage.profile_configs.items())

        def handle_message(self, message: Message) -> bool:
            def check_type(message: Message, oftype):
                if not isinstance(message.value, oftype):
                    raise ValueError(f"Profile parameter {message.name} must be of type {oftype}.")
                return message.value
            
            def check_dist(message: Message):
                if isinstance(message.value, (int, float)):
                    return ConstantDistribution(message.value)
                return dist_parser(message.value)

            if super().handle_message(message):
                return True
            # A message with a colon in the name is directed to a specific
            # config. Otherwise, it applies to all
            prefix, *suffix = message,name.split(":", maxsplit=1)
            if len(suffix) == 0:
                target_group = None
                target_param = prefix
            else:
                target_group = prefix
                target_param = suffix[0]

            if isinstance(self.profile_configs, ProfileGroupConfig):
                if target_group is not None:
                    raise ValueError(f"Profile group {target_group} does not exist.")
                targets = [self.profile_configs]
            else:
                assert isinstance(self.profile_configs, dict)
                if target_group is None:
                    targets = list(self.profile_configs.values())                
                elif target_group not in self.profile_configs:
                    raise ValueError(f"Profile group {target_group} does not exist.")
                else:
                    targets = [self.profile_configs[target_group]]

            for target in targets:
                match (target_param):
                    case "n_species":
                        target.n_species = check_type(message, int)
                    case "n_target_masses":
                        target.n_target_masses = check_type(message, int)
                    case "initial_components":
                        target.initial_components = check_dist(message)
                    case "initial_masses":
                        target.initial_masses = check_dist(message)
                    case "initial_intensities":
                        target.initial_intensities = check_dist(message)
                    case "intensity_scale":
                        target.intensity_scale = check_dist(message)
                    case "min_intensity":
                        target.min_intensity = check_type(message, (int, float))
                    case "pre_weight":
                        target.pre_weight = check_type(message, (int, float))
                    case "weight_exponent":
                        target.weight_exp = check_type(message, (int, float))
                    case _:
                        return False                    
            return True    
                    

class ApplyProfileStage(Stage):
    """
    Stage to take output from a species simulation stage, and apply 
    """
    REQUIRES = [ "abundance","species_info", "base_response", "profile_responses"]
    PROVIDES = ["abundance", "base_response", "species_info"]

    def default_name(self) -> str:
        return "ApplyProfiles"

    def execute(self, input: StageData,
                rng: np.random.Generator,
                state: Stage.State) -> PipelineData:
        profile_responses = input.extra["profile_responses"]
        # Simplest case: we have a single set of profiles that applies to all
        # species
        assert input.abundance is not None
        assert input.species_info is not None
        assert input.base_response is not None

        if None in profile_responses:
            assert len(profile_responses) == 1
            response = profile_responses[None]
            assert isinstance(response, ProfileGroupConfig.ResponseSet)
            
            abundance = response.apply(input.abundance)
            base_response = response.apply(input.base_response)
            species_info = pd.DataFrame({"mass": response.masses})
            species_info.index.name = "species_id"

            result = input.copy(abundance=abundance,
                                base_response=base_response,
                                species_info=species_info)

        else:
            # This is harder, and it will take several steps.  We have
            # to merge data from different groups. We first have to
            # make sure that there is a 1-1 correspondence between
            # species groups from the abundance data, and from the
            # profile data.
            
            spcs_groups = input.species_info["group"].unique()
            if set(spcs_groups) != set(profile_responses):
                raise ValueError("ApplyProfile requires that each species group correspond to "
                                 f"exactly one profile group. Species groups={list(spcs_groups)} "
                                 f", Profile groups={list(profile_responses.keys())}.")

            group_abundances = {}
            group_bases = {}
            # Now extract the abundance data for each group, and apply
            # the corresponding profile to it.
            for spcs_group, response in profile_responses.items():
                assert isinstance(response, ProfileGroupConfig.ResponseSet)
                # For each specis group, we track which columns in the
                # abundance data belong this group, and count them to
                # make sure they match with the profiles
                columns = input.species_info["group"] == spcs_group
                if columns.sum() != len(response.profiles):
                    raise ValueError("ApplyProfile: mismatch between number of species in "
                                     f"species_group `{spcs_group}` ({columns.sum()}) and "
                                     f"number of profiles ({len(response.profiles)}).")
                # Then we extract the columns from the abundance/base
                # response data, and apply the profile.
                group_abundances[spcs_group] = (response.apply(input.abundance[:, columns]), response.masses)
                group_bases[spcs_group] = (response.apply(input.base_response[:, columns]), response.masses)

                
            # Now the tricky bit: we have multiple sets of masses, one
            # for each species group, and they likely overlap, (but
            # *not* exactly - just within tolerance). We need to merge
            # and align them.  Technically, each group's profiles can
            # each be generated with a separate tolerance; we'll use
            # the most restrictive one, then call a function to merge data.
            tolerance_ppm = min(resp.config.tolerance_ppm for resp in profile_responses.items())
            all_masses, locations = _merge_masses({k: profile_responses[k].masses for k in profile_responses},
                                                  tolerance_ppm * 1e-6)

            # Generate placeholder outputs that we'll fill in progressively.
            abundance = np.zeros((input.abundance.shape[0], all_masses.shape[0]))
            base_response = np.zeros((input.base_response.shape[0], all_masses.shape[0]))
            species_info = pd.DataFrame({"mass": all_masses})
            species_info.index.name = "species_id"

            # This is just to keep track of how many groups contribute
            # to each entry, for later.
            group_count = np.zeros((input.abundance.shape[0], all_masses.shape[0]), dtype=np.uint8)

            # For each species group, get the computed abundance, and
            # the mass locations (columns in combined abundace), and
            # just add the abundace to the output. This is essentially
            # the same as how we combine metabolites from different
            # profiles *within* a species group.
            for spcs_group in group_abundances:
                group_locs = locations[spcs_group]
                abundance[:, group_locs] += group_abundances[spcs_group]
                group_count[:, group_locs] += (group_abundances[spcs_group] > 0)
                base_response[:, group_locs] += group_bases[spcs_group]
                
                # Also, for each metabolite, add a column to record if it came from this group
                species_info[spcs_group] = False
                species_info[spcs_group][locations[spcs_group]] = True

            # Now, base_response should be between 0-1. We added a bunch of base responses together,
            # now divide by the number of non-zero additions. 
            base_response /= np.maximum(group_count, 1)

            result = input.copy(abundance=abundance,
                                base_response=base_response,
                                species_info=species_info)
            
        # Phew, we're done! - return the result from either of the above cases.
        return PipelineData(result,
                            messages=[],
                            rng=rng)

            
            
                

            

# This is a python implementation of the profile generator, left here largely
# as a reference. It's not pure python (it uses the C++ `MassTracker`), but
# most of the other logic for applying transformations is here.
# It's not ridiculously slow (on a fast machine, generating ~30,000 peaks
# takes ~3 seconds)

@dataclasses.dataclass
class _ProfileWorker:
    intensities: dict[int, float]
    tracker: MassTracker


@dataclasses.dataclass
class _XfrmSelection:
    xfrm_id: int
    delta_m: float
    fwd: int
    back: int



class PyProfileGroupConfig:
    class ResponseSet:
        def __init__(self, config, masses, profiles, stats=None):
            self.config = config
            self.masses = masses
            self.profiles = profiles
            self.stats = stats

        def apply(self, spcs_abundance):
            """
            Given a matrix where rows are samples and columns are species,
            return a new matrix with (n_samples, n_masses)
            """
            result = np.zeros((spcs_abundance.shape[0], len(self.masses)))
            assert spcs_abundance.shape[1] == len(self.profiles)
            # Basically, for each species, multiply its abundance (across
            # all samples) by its metabolic profile.
            for idx, prof in enumerate(self.profiles):
                result[:, prof.indices] += (spcs_abundance[:, idx][:, None]
                                            * prof.intensities)
            return result

    def __init__(self,
                 n_species: int,
                 n_target_masses: int,
                 transform_data: pd.DataFrame,
                 initial_components: int | Distribution,
                 initial_masses: List[float] | Distribution,
                 initial_intensities: int | float | Distribution | None = None,
                 intensity_scale: Distribution | None = None,
                 min_intensity: float = 1e-6,
                 tolerance_ppm: float = 1.0,
                 min_mass: float = 150,
                 max_mass: float = 1200,
                 pre_weight: float = 1,
                 weight_exponent: int = 2):

        """Configure a generator which produces "metabolic profiles"
        for a group of species.

        A metabolic profile is essentially a "mini-spectrum", or a
        list of masses and intensities.  Each species gets its own
        profile, and the set of species profiles can combined with
        species abundance to produce output spectra.

        Profile generation occurs in two steps, initialization and transformation.

        In initialization, profiles (one per species) are initialized
        with some number (relatively small, but at least one) peaks. The number of peaks in each
        profile, as well as peak attributes, are drawn from distributions given by the
        `initial_...` args.


        Transformation applies an iterative process to generate new
        peaks from existing ones.  Each iteration consists of choosing
        a transformation to apply, a profile, and a parent peak within
        t the profile.  New peak masses are generated by applying the
        mass_delta from the transformation to the parent peak one or
        more times (forward and/or backward).  The intensity of the
        new peaks is generated by scaling the parent peak by `intensity_scale`.
        The process is repeated until `n_target_masses` peaks are generated.

        Transformations are chosen based on probabilities given in the
        input `transform_data`. One might expect that simply applying
        transformations drawn using those probabilities will yield a
        dataset that has the same proportion of
        transformations. However this is not the case; many
        biochemical transformations can by built up as linear
        combinations of others.  Thus if you look at the
        transformation graph (aka Mass Diference Network, or MDiN) of
        the result, many new edges arise spontaneously. Even if you
        restrict yourself to some linearly independent set of
        transformations, the error caused by having a non-zero
        tolerance (even sub-parts-per-million) causes many
        unanticipated transformations to appear. In particular,
        extremely common transformations like methylation (+14.01565
        Da) that are substituents of many others appear relatively
        much less frequently than desired.

        To get around that, and to attempt to produce output datasets
        with similar transformation networks as real data, massim uses
        a weigting strategy.  As new peaks are added, massim tracks
        the changes to the MDiN, updating the number of
        transformations added directly *or indirectly*. Then, when it
        comes time to select a mass delta (aka Mass Difference
        Building Block, or MDB), massim weights the probability of
        each MDB by:

                                                        
        |  (desired fraction of MDB) * (1 + preweight) |**(weight_exponent)
        |  ------------------------------------------  |
        |   (current fraction of MDB + preweight)      |

        (The preweight is there mainly to control the early stages of
        the process, when the current fraction is low/zero)

        Thus, if a 
        

        
        However, naively drawing transformations (really, mass deltas)
        according to those probabilities will not yield
        
        Massim applies a probability weighting scheme to try to get the transformation counts
        of the output to 

        Args:
            n_species: Number of species to create profiles for.
            n_target_masses: Desired total number of peaks. The actual
                output might exceed this slightly.
            transform_data: A pandas DataFrame containing the
                biochemical transformations to apply. It must contain
                the columns:
            initial_components: Number of peaks to initially assign to
                each profile. Can be an integer, or a distrubution
                that will be drawn from for each profile. A minimum of
                one peak will be added to each profile.
            initial_masses: A fixed mass, list of masses, or
                distribution that will be used to populate the initial
                peaks. If it is a float, all profiles will be
                initialized with the same mass. If it's a list, massim
                will build a ChoiceDistribution from it.
            initial_intensities: A fixed scalar intensity or
                distribution used to choose the intensities of the
                initial peaks. Note that it can return negative vales,
                which can be used as a form of competition.
            intensity_scale: Scale factor to use when applying
                transformations. Each time a transformation is applied
                to a peak, the new peak's intensity will be this scale
                factor times the paren peak's intensity (and the
                parent intensity is reduced accordingly). May be a
                scalar or distribution, but should only return values
                from 0 to 1.
            min_intensity: Minimum intensty of any new peak. If a new
                peak falls below this threshold, the current
                transformation is aborted.
            tolerance_ppm: Mass tolerance in parts per million. If a
                new peak is within this tolerance of an existing peak,
                it will be merged with the existing one.
            min_mass: Minimum mass to be produced during
                transformation.
            max_mass: Maximum mass to produce during transformation.
            pre_weight: Part of the probability weighting scheme.
            weight_exponent: Used to select transformation to apply.

        """
        """Configure a generator which produces "metabolic profiles"
        for a group of species.

        A metabolic profile is essentially a "mini-spectrum", or a
        list of masses and intensities.  Each species gets its own
        profile, and the set of species profiles can combined with
        species abundance to produce output spectra.

        Profile generation occurs in two steps. In the first step,
        profiles (one per species) are initialized with relatively few
        peaks, which are assigned according to the `initial_..`
        parameters.  Then, new metabolites are generated by applying
        simulated biochemical transformations to randomly selected
        peaks from randomly selected profiles. This process repeats until the
        total number of distinct peaks (across all profiles) reaches a target level.

        Parameters:
        

        """
        self.n_species = n_species
        self.n_target_masses = n_target_masses
        if isinstance(initial_components, (int, float)):
            initial_components = ConstantDistribution(initial_components)
        elif not isinstance(initial_components, Distribution):
            raise ValueError("'initial_components' must be an integer or distribution.")
        self.initial_components = initial_components

        if intensity_scale is None:
            intensity_scale = UniformDistribution(0, 1)
        if not isinstance(intensity_scale, Distribution):
            raise ValueError("`intensity_scale` must be a distribution.")
        try:
            intensity_scale.to_cdist()
        except RuntimeError:
            raise ValueError(f"Sadly, distribution type `{intensity_scale.shortname}` "
                             "isn't supported for profiles yet.")
        self.intensity_scale = intensity_scale

        if not isinstance(initial_masses, Distribution):
            if isinstance(initial_masses, (int, float)):
                initial_masses = ChoiceDistribution([initial_masses])
            elif hasattr(initial_masses, "__len__"):
                if not all(isinstance(x, (int, float)) for x in initial_masses):
                    raise ValueError("`initial_masses` must be a float, list of floats, or distribution.")
                initial_masses = ChoiceDistribution([x for x in initial_masses])
            else:
                raise ValueError("`initial_masses` must be a float, list of floats, or distribution.")
        self.initial_masses = initial_masses

        if initial_intensities is None:
            initial_intensities = LogNormalDistribution(0, 1)
        if isinstance(initial_intensities, (int, float)):
            initial_intensities = ConstantDistribution(initial_intensities)
        if not isinstance(initial_intensities, Distribution):
            raise ValueError("`initial_intensities` must be a distribution.")
        self.initial_intensities = initial_intensities
        
        # Initialize information about transformations
        # While passed as a dataframe, we store a list of rows, since oddly
        # pd.DataFrame.iloc is extremely slow in tight loops.
        self.xkeys = transform_data
        self.xkeys = self.xkeys.replace(np.nan, 0)
        self.xkeylist = [x for _, x in self.xkeys.iterrows()]

        self.raw_probs = (self.xkeys.chain_prob.values * (self.xkeys.chain_len - 1).values)
        self.raw_probs = self.raw_probs / self.raw_probs.sum()

        self.min_intensity = min_intensity
        self.tolerance_ppm = tolerance_ppm
        self.min_mass = min_mass
        self.max_mass = max_mass

        # Initialize the weighting factors for picking transforms
        if pre_weight <= 0:
            raise ValueError("Pre-weight must be positive.")
        self.pre_weight = pre_weight
        self.weight_exp = weight_exponent

    def generate_response(self, rng=None, return_worker=False):
        rng = RNG(rng)
        xformer = ProfileGroupConfig._PyXformer(self)

        # Populate the profiles with initial components
        for spcs_id in range(self.n_species):
            # Choose number of components per profile by sampling the distribution
            num_core = self.initial_components(1, rng=rng)[0]
            num_core = max(1, int(num_core))

            masses = self.initial_masses(num_core, rng=rng)
            intensities = self.initial_intensities(num_core, rng=rng)
            intensities /= intensities.sum()
            for w, m in zip(intensities, masses):
                xformer.update_component(spcs_id, m, w)

        # Now, just run it:
        xformer.apply_transforms(self.n_target_masses, rng=rng)
        stats = dict(xformer.stats)

        # Some stats about how many xfrms we applied, and how many were detected.
        stats["applied"] = dict(zip(*np.unique(xformer.applied, return_counts=True)))
        stats["xfrm_counts"] = xformer.global_tracker.counts()
        result = ProfileGroupConfig.ResponseSet(self,
                                                xformer.masses(),
                                                xformer.profiles(),
                                                stats=stats)
        # For debugging:
        if return_worker:
            return result, xformer
        
        return result
        


    class _PyXformer:
        """
        Helper class to apply transforms to the profiles.
        Use it to set up profiles, initialize them with masses/intensities, and
        then apply transformations
        """
        def __init__(self, parent: ProfileGroupConfig):
            self.parent = parent
            self.global_tracker = MassTracker(parent.xkeys.mass_delta, parent.tolerance_ppm, MODE_STRICT)
            self.profs = []
            for _ in range(parent.n_species):
                tr = MassTracker(parent.xkeys.mass_delta, parent.tolerance_ppm, MODE_STRICT)
                self.profs.append(_ProfileWorker(dict(), tr))
            self.stats = defaultdict(int)
            self.applied = []

        def choose_xfrm(self, rng):
            """
            Choose the next transform to apply, weighted by the current mix of transforms.
            I.e. if a transform has an innate probability of 10%, and it only accounts
            for 5% of the transformations among the current masses, we weight the probabilities
            to make it more likely to be chosen.
            """
            parent = self.parent
            # Weight by how many of each transform we have actually seen
            cnts = self.global_tracker.counts()
            cur_frac = ((cnts + parent.pre_weight * parent.raw_probs) /
                        (parent.pre_weight + self.global_tracker.total_count()))

            cur_frac[cur_frac == 0] = 1.0
            wts = (parent.raw_probs / cur_frac) ** parent.weight_exp
            probs = parent.raw_probs * wts
            probs = probs / probs.sum()
            xfrm_id = rng.choice(len(probs), p=probs)
            xfrm = parent.xkeylist[xfrm_id]
            tot_len = 1 + rng.negative_binomial(xfrm.chain_len - 1.999, 0.5)
            fwd = rng.integers(tot_len+1)
            return _XfrmSelection(xfrm_id, xfrm.mass_delta, fwd, tot_len - fwd)

        def update_component(self, prof_or_id, m, intens):
            """Add a component with mass `m` and intensity `intens`
            to the given profile.  If the component already exists in
            the profile, the intensity is added to the existing.

            This method updates the transformation trackers. If `m` is close to an
            existing mass, that mass is used instead.
            Returns the actual mass used, and its tracked id

            """
            if isinstance(prof_or_id, _ProfileWorker):
                cur_prof = prof_or_id
            else:
                cur_prof = self.profs[prof_or_id]

            mass_id = self.global_tracker.insert_mass(m)
            # If m is within tolerance of an existing mass, it isn't inserted,
            # and the id of the closest mass is returned.
            actual_mass = self.global_tracker.find_mass_by_id(mass_id)

            seen_profile = mass_id in cur_prof.intensities
            if seen_profile:
                cur_prof.intensities[mass_id] += intens
            else:
                cur_prof.intensities[mass_id] = intens

            cur_prof.tracker.insert_mass(actual_mass, mass_id=mass_id)

            return actual_mass, mass_id

        def extend_chain(self, mass_id, xfrm, prof, dircnt, rng):
            parent = self.parent
            delta = xfrm.delta_m
    
            if dircnt == 0:
                return
            elif dircnt < 0:
                dircnt = -dircnt
                delta = -delta

            parent_mass = self.global_tracker.find_mass_by_id(mass_id)
            parent_id = mass_id
            new_mass = parent_mass
            idist = self.parent.intensity_scale
            
            while dircnt > 0:
                dircnt -= 1
                new_mass += delta
                if (new_mass < parent.min_mass) or (new_mass > parent.max_mass):
                    self.stats["break_mass"] += 1
                    return

                parent_intens = prof.intensities[parent_id]

                scale = idist(1, rng)[0]
                if parent_intens * scale < parent.min_intensity:
                    self.stats["break_int"] += 1
                    return

                added_mass, added_id = self.update_component(prof,
                                                             new_mass,
                                                             parent_intens*scale)
                prof.intensities[parent_id] *= (1-scale)

                parent_mass = added_mass
                parent_id = added_id
                parent_intens *= scale

                self.stats["loops"] += 1
                self.applied.append(xfrm.xfrm_id)

        def apply_transforms(self, target_masses, rng):
            while self.global_tracker.size() < target_masses:
                # Fix the profile and xfrm to use
                prof_id = rng.integers(len(self.profs))
                prof = self.profs[prof_id]
                xfrm = self.choose_xfrm(rng)

                # Now, choose a metabolite that has not yet had the transform
                # applied. First, get all the mass ids in random order
                p_keys = np.fromiter(prof.intensities.keys(), dtype=int)
                rng.shuffle(p_keys)

                # Now, just find the metabolite that hasn't had this xfrm applied
                # (directly or indirectly) to both sides yet. There must be at least 2.
                mass_id = -1
                for mass_id in p_keys:
                    src, dst = prof.tracker.contains_xfrm_by_id(mass_id, xfrm.xfrm_id)
                    if not (src and dst):
                        break
                assert mass_id >= 0
                # Finally, apply the transform to the selected mass in
                # each direction
                self.extend_chain(mass_id, xfrm, prof, xfrm.fwd, rng)
                self.extend_chain(mass_id, xfrm, prof, -xfrm.back, rng)

        def masses(self):
            return self.global_tracker.masses()

        def profiles(self):

            # The mass_ids assigned by the tracker are in no particular order.
            # Thus, to find the indices in the *sorted* mass list, we build
            # a lookup (the tracker's `mass_ids` function returns the ids
            # sorted by mass(
            index_lookup = dict(zip(self.global_tracker.mass_ids(),
                                    range(self.global_tracker.size())))
            result = []
            for p in self.profs:
                indices = np.array([index_lookup[k] for k in p.intensities.keys()])
                intensities = np.fromiter(p.intensities.values(), dtype=float)
                # Now, indices can be sorted in their natural order (corresponding
                # to increasing mass)
                ordd = np.argsort(indices)
                res = ProfileResult(indices[ordd], intensities[ordd])
                result.append(res)
            return result
