name: Build and Publish Wheels

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # matrix setup for Windows, Ubuntu Linux, and macOS
        os: [macos-latest] #[ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          compiler: ${{ matrix.compiler }}
          build-type: ${{ matrix.build-type }}
          ubuntu: |
            apt: libeigen3-dev
          macos: |
            brew: eigen
          windows: |
            github:
              - path: eigenteam/eigen-git-mirror
                ref: 3.3.7

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v4.1.0
        env:
          # Configuration for compilation targets
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          # Optional: Run tests inside the wheels before finalizing
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload artifact sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  publish_to_pypi:
    name: Publish packages to TestPyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # Securely deploy to PyPI only when a GitHub Release is published
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://test.pypi.org
    permissions:
      id-token: write  # Mandatory for Trusted Publishing (OIDC)
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          merge-multiple: true
          path: dist

      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
